Q1

In [4]:
import numpy as np

arr=np.array([10,20,30,40,50])
narr=arr+2
print(narr)
narr=arr*3
print(narr)
narr=arr/2
print(narr)

[12 22 32 42 52]
[ 30  60  90 120 150]
[ 5. 10. 15. 20. 25.]


Q2

In [32]:
arr = np.array([1, 2, 3, 6, 4, 5])
narr=np.flip(arr)
print(narr)

x = np.array([1,2,3,4,5,1,2,1,1,1])
freq=np.bincount(x)
print(freq)
most_freq_val=freq.argmax()
print("Most frequent value is: "+str(most_freq_val))
indices=np.where(x==most_freq_val)[0]
print(indices)

y= np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
unique,counts=np.unique(y,return_counts=True)
print(unique)
print(counts)
most_freq_val=unique[np.argmax(counts)]
print(most_freq_val)

indices=np.where(y==most_freq_val)[0]
print(indices)
 


[5 4 6 3 2 1]
[0 5 2 1 1 1]
Most frequent value is: 1
[0 5 7 8 9]
[1 2 3 4]
[3 2 3 2]
1
[0 1 2]


Q3

In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(arr[0][1])
# printing 1st row, 2nd column


print(arr[2][0]) # printing 3rd row, 1st column


Q4

In [ ]:
import numpy as np

array=np.linspace(10,100,num=25)

print(array)

print(np.shape(array))

print(np.count_nonzero(array))

print(np.size(array))

print(array.dtype)

print(array.nbytes)

print(array.reshape(np.size(array),1))

print(array.T)

Q5

In [ ]:
import numpy as np
ucs420_Rehnoor = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])

print(ucs420_Rehnoor.mean()) #mean
# finding median
print(np.median(ucs420_Rehnoor))
print(ucs420_Rehnoor.max())# max
print(ucs420_Rehnoor.min()) # min
print(np.unique(ucs420_Rehnoor)) #unique


In [ ]:
import numpy as np
reshaped_ucs420_Rehnoor = ucs420_Rehnoor.reshape((4,3))
print('Reshaped: ',reshaped_ucs420_Rehnoor)

resized_ucs420_Rehnoor = np.resize(ucs420_Rehnoor,(2,3))
print('Resized: ',resized_ucs420_Rehnoor)